title: Roberto Frias Corral # your name (or website title) here
logo: "/images/2819A12B-DF23-4166-B6F3-1457EF303FC4.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Computer Science Student @ Long Beach City College 
  <br><br>
  Experienced in app development, web design, machine learning, and generative AI. 
  <br><br>
  <a href="https://www.linkedin.com/in/rfriascorral/">Connect with me on LinkedIn!</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
